name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Enable Corepack and setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.1.1 --activate
    
    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Verify lockfile
      run: |
        if [ ! -f yarn.lock ]; then
          echo "Error: yarn.lock file was not generated"
          exit 1
        fi
        echo "yarn.lock file exists and will be committed"
    
    - name: Run tests with coverage
      uses: borales/actions-yarn@v4
      with:
        cmd: test:coverage
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 